attendance/urls.py
from django.urls import path
from . import views

app_name = 'attendance'
urlpatterns = [
    path('', views.index, name='index'),
    path('completed', views.completed_detail, name='completed'),
    path('rankings', views.rankings_view, name='rankings'),
    path('winner', views.winner, name='winner'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('attendance/', include('attendance.urls')),
    path('admin/', admin.site.urls),
    path('admin/password_reset/', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

attendance/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin


class Event(models.Model):
    events = models.CharField(max_length=50)

    def __str__(self):
        return self.events


class Snippet(models.Model):
    name = models.CharField(max_length=200)
    FR = models.BooleanField(default=False)
    SO = models.BooleanField(default=False)
    JR = models.BooleanField(default=False)
    SR = models.BooleanField(default=False)
    email = models.EmailField(default='')
    points = models.IntegerField(default=0)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default='')
    created_at = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name

    @admin.display(
        ordering='created_at',
        description='Submitted',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(hours=6) <= self.created_at <= now

users/models.py
from django.db import models

# Create your models here.

attendance/forms.py
from django import forms
from .models import Snippet


class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        fields = ('name', 'FR', 'SO', 'JR', 'SR', 'event', 'email',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First and Last name'}),
            'FR': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'SO': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'JR': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'SR': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'event': forms.Select(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'example@usd109.org'}),
        }

users/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

attendance/views.py
from .forms import SnippetForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Snippet
import datetime
from django.contrib.auth.decorators import login_required
import random


def index(request):
    if request.method == 'POST':
        form = SnippetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                # Check if user with the same email already exists
                existing_snippet = Snippet.objects.get(email=email)
                existing_snippet.points += 1
                # need this line to go into the db, delete the event info and rewrite it
                existing_snippet.save()
                return HttpResponseRedirect(reverse('attendance:completed'))
            except Snippet.DoesNotExist:
                # If user does not exist, create a new one
                new_snippet = form.save()
                new_snippet.points += 1
                new_snippet.save()
                return HttpResponseRedirect(reverse('attendance:completed'))
    else:
        form = SnippetForm
        return render(request, 'attendance/form.html', {'form': form})


def completed_detail(request):
    return render(request, 'attendance/completed.html')


def rankings_view(request):
    top_seven = Snippet.objects.all().order_by('-points')[:7]
    return render(request, 'attendance/rankings.html', {'top_seven': top_seven})


def archive(request, year, month, day):
    date = datetime.datetime(year, month, day)
    entries = Snippet.objects.filter(created_at__date=date)
    return render(request, 'archive.html', {'entries': entries})


@login_required
def winner(request):
    fr_recipient = random.choice(Snippet.objects.filter(FR=True))
    so_recipient = random.choice(Snippet.objects.filter(SO=True))
    jr_recipient = random.choice(Snippet.objects.filter(JR=True))
    sr_recipient = random.choice(Snippet.objects.filter(SR=True))
    return render(request, 'attendance/winner.html', {
        'fr_recipient': fr_recipient,
        'so_recipient': so_recipient,
        'jr_recipient': jr_recipient,
        'sr_recipient': sr_recipient,
    })

users/views.py
from django.shortcuts import render

# Create your views here.

attendance/templates/attendance/completed.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Submitted!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <p> Thank you for filling out the form, you will now have a chance to win the prize. Want to see the <a href="{% url 'attendance:rankings' %}" class="link-light">rankings</a>? </p>
</body>
</html>

attendance/templates/attendance/form.html
{% load crispy_forms_tags %}
{% load bootstrap5 %}

<html lang="en" data-bs-theme="dark">
<head>
    <style>
        #HelpBtn {
      position: absolute;
      bottom: 0;
      left: 0;
    }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RCHS Attendance Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<header>
    {% include 'attendance/navbar.html' %}
</header>
<hr>
<h3>RCHS Attendance Form</h3>
<div class="text-success">
  <hr>
</div>

    <!-- Attendance Form -->
    <form method="post">
        {% csrf_token %}
        <br/>
        {{ form|crispy }}
        <br/>
        <button type="submit" class="btn btn-secondary">Submit</button>
    </form>
    <br/>


    <!-- Help: Live Toast -->
<button type="button" class="btn btn-outline-primary btn-sm" id="HelpBtn">More Info</button>

<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <img src="..." class="rounded me-2" alt="...">
      <strong class="me-auto">More Info</strong>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
<h6>Overview:</h6>
<p>This form was created with the intentions of inspiring Republic County students to attend school related activities. For each event the student fills out the form for, they will be rewarded with one point. Each week one person from each grade, who have filled out the form, will be rewarded with a prize, as well as the individual with the most points.</p>

<h6>How The Form Should Be Filled Out:</h6>
<p>Please enter your fist and last name, select the grade you’re in, etc. and finally click submit. All entries will be reviewed to ensure they are legit. If there is no event listed your form will not be counted.</p>
    </div>
  </div>
</div>


    <!-- Javascript -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>


<script>
const toastTrigger = document.getElementById('HelpBtn')
const toastLiveExample = document.getElementById('liveToast')
if (toastTrigger) {
  toastTrigger.addEventListener('click', () => {
    const toast = new bootstrap.Toast(toastLiveExample, { autohide: false })

    toast.show()
  })
}
</script>


<!-- ? -->

</body>
</html>

attendance/templates/attendance/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" data-bs-theme="dark">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'attendance:index' %}">Form</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'attendance:rankings' %}">Rankings</a>
        </li>
          {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'attendance:winner' %}">Winner</a>
    </li>
{% else %}
    <li class="nav-item">
        <a class="nav-link disabled" aria-current="page" href="{% url 'attendance:winner' %}">Winner</a>
    </li>
{% endif %}
        {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
    </li>
{% else %}
    <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Log in</a>
    </li>
{% endif %}
      </ul>
    </div>
  </div>
</nav>
</body>
</html>

attendance/templates/attendance/rankings.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<header>
    {% csrf_token %}
    {% include 'attendance/navbar.html' %}
</header>
<center>
<h1>Leaderboard</h1>
<ul>
     {% for snippet in top_seven %}
        <li><h4>{{ snippet.name }}: {{ snippet.points }} points</h4></li>
    {% endfor %}
</ul>
</center>
</body>
</html>

attendance/templates/attendance/winner.html
<!DOCTYPE html>

<html lang="en" data-bs-theme="dark">>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Overall Winner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<header>
    {% include 'attendance/navbar.html' %}
</header>
<h4>Freshman Winner: {{ fr_recipient.name }}</h4>
<h4>Sophomore Winner: {{ so_recipient.name }}</h4>
<h4>Junior Winner: {{ jr_recipient.name }}</h4>
<h4>Senior Winner: {{ sr_recipient.name }}</h4>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>
<body>
<header>
    {% include 'attendance/navbar.html' %}
</header>

{% block content %}

{% if form.errors %}
    <p> Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="POST" action="{% url 'users:login %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-secondary">Submit</button>
    <input type="hidden" name="next" value="{% url 'attendance:index' %}" />
</form>

{% endblock content %}

</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>